/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDRESS 0x40023800UL
#define RCC_AHB1_ENABLE_RE ((uint32_t*)(RCC_BASE_ADDRESS + 0x30))

#define GPIO_A_BASE_ADDRESS 0x40020000
#define GPIO_A_MODE_REG (uint32_t*)GPIO_A_BASE_ADDRESS
#define GPIO_A_OUTPUT  ((uint32_t*)(GPIO_A_BASE_ADDRESS + 0x14))


void delay(void){
	for (uint64_t i = 0; i < 65535; i++) {
	}
	for (uint64_t i = 0; i < 65535; i++) {
	}
}

int main(void) {
	*RCC_AHB1_ENABLE_RE |= (*RCC_AHB1_ENABLE_RE | 0X01); //Enable clock for GPIOA
	*GPIO_A_MODE_REG |= (*GPIO_A_MODE_REG | (1 << 10)); //Change GPIOA, pin 5 mode to output mode

	while (1) {
		*GPIO_A_OUTPUT |= (*GPIO_A_OUTPUT | (1<<5)); //Set 5th bit
		delay();
		*GPIO_A_OUTPUT &= ~(*GPIO_A_OUTPUT | (1<<5)); //Clear 5th bit
		delay();
	}
}
