/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*PA2 & PA3 is connected to UART2 of the Nucleo board*/
#include <stdint.h>

#define RCC_BASE_ADDRESS 0x40023800UL
#define RCC_AHB1_ENABLE_RE ((uint32_t*)(RCC_BASE_ADDRESS + 0x30))
#define AHB1_ENAA_GPIO_A_BIT 1

#define GPIO_A_BASE_ADDRESS 0x40020000
#define GPIO_A_ALTERNATE_FUNCTION_LOW_REG (uint32_t *)(GPIO_A_BASE_ADDRESS+0x20)
#define AF_7 0b0111

#define RCC_APB1_CLK_EN_REG (uint32_t *)(RCC_BASE_ADDRESS+0X40)
#define RCC_APB1A_UART2A_EN_BIT 1<<17

#define UART2_BASE_ADDRESS 0X40004400
#define UART2_STATUS_REG (uint32_t *)UART2_BASE_ADDRESS
#define UART2_DATA_REG (uint32_t *)(UART2_BASE_ADDRESS+0x04)
#define UART2_BAUD_RATE_REG (uint32_t *)(UART2_BASE_ADDRESS+0x08)
#define UART2_CTRL_REG1 (uint32_t *)(UART2_BASE_ADDRESS+0x0C)
#define UART2_CTRL_REG2 (uint32_t *)(UART2_BASE_ADDRESS+0x10)
#define UART2_CTRL_REG3 (uint32_t *)(UART2_BASE_ADDRESS+0x14)
#define UART2_GUARD_TIME_AND_PRESCALER_REG (uint32_t *)(UART2_BASE_ADDRESS+0x18)

/*Define bits required by the UART STATUS REG*/
#define STATUS_REG_TXE 1<<7 /*Transmit data register is empty*/
#define STATUS_REG_RXNE 1<<5 /*Read data register is not empty*/

/*Define bits required by the UART CONTROL REG1*/
#define CTRL_REG_1_RE 1<<2 //Enabling this bit enables the receiver
#define CTRL_REG_1_TE 1<<3 //Enabling this bit enables the transmitter
#define CTRL_REG_1_UE 1<<13//Enabling this bit enables the UART

#define SYS_FREQ 8000000
#define PERIPHERAL_CLOCK SYS_FREQ
#define BAUDRATE 115200

void UART_SetBaudRate(uint32_t peripheralClock, uint32_t baudrate) {
	*UART2_BAUD_RATE_REG |= ((peripheralClock + (baudrate / 2U)) / baudrate);
}

void UART2_Init(void) {
	/*Enable clock for UART2 peripheral*/
	*RCC_APB1_CLK_EN_REG |= RCC_APB1A_UART2A_EN_BIT;

	/*Enable alternate function for the pin which will get as UART RX and TX*/
	/*You can get the alternate function mapping table by searching `alternate function mapping` keyword in data-sheet*/
	/* PA2 = UART2_TX
	 * PA3 = UART3_RX*/

	/*Enable clock for Port A*/
	*RCC_AHB1_ENABLE_RE |= AHB1_ENAA_GPIO_A_BIT;

	/*Set alternate function for these 2 pins*/
	*GPIO_A_ALTERNATE_FUNCTION_LOW_REG |= AF_7 << 15;
	*GPIO_A_ALTERNATE_FUNCTION_LOW_REG |= AF_7 << 11;

	/*Enable transmission and reception using UART*/
	*UART2_CTRL_REG1 |= CTRL_REG_1_UE;
	*UART2_CTRL_REG1 |= CTRL_REG_1_RE;
	*UART2_CTRL_REG1 |= CTRL_REG_1_TE;

	/*Set baud-rate*/
	UART_SetBaudRate(PERIPHERAL_CLOCK, BAUDRATE);
}

void UART2_Write(char c) {
	/*Make sure the transmit data register is empty*/
	while (!((*UART2_STATUS_REG ) & STATUS_REG_TXE))
		;
	*UART2_DATA_REG |= c;
}

char UART2_Read(void) {
	/*Make sure there is something in buffer*/
	while (!((*UART2_STATUS_REG ) & STATUS_REG_RXNE))
		;
	return *UART2_DATA_REG ;
}

int main(void) {
	UART2_Init();
	while (1) {
		UART2_Write('S');
	}
}
